#define NUMBER_KEYWORD 1
#define STRING_KEYWORD 2
#define BOOLEAN_KEYWORD 3
#define NUMBER 4
#define STRING 5
#define BOOLEAN 6
#define ADD 7
#define SUBTRACT 8
#define MULTIPLY 9
#define DIVIDE 10
#define POWER 11
#define BITWISE_XOR 12
#define BITWISE_AND 13
#define BITWISE_OR 14
#define BITWISE_NOT 15
#define LOGICAL_EQUAL 16
#define NOT_EQUAL 17
#define AND 18
#define OR 19
#define EQUAL 20
#define VARIABLE 21